"""Typed access to public Guangdong University of Finance website content."""

from gduf_web_api.api import (
    get_ai_detail,
    get_ai_home,
    get_ai_jfry,
    get_ai_jgsz,
    get_ai_jsjkxyjs,
    get_ai_rgzn,
    get_ai_rjgc,
    get_ai_sjkxydsjjs,
    get_ai_tzgg,
    get_ai_xshenghd,
    get_ai_xshuhd,
    get_ai_xyjj,
    get_ai_xyld,
    get_ai_xyxw,
    get_ai_yytjx,
    get_ai_zrjs,
    get_aijspt_bslb,
    get_aijspt_bsxq,
    get_aijspt_stlb,
    get_aijspt_tzgg,
    search_ai,
)
from gduf_web_api.client import GdufClient
from gduf_web_api.errors import (
    GdufError,
    InvalidPageError,
    NetworkError,
    ParseError,
    UnsupportedSourceError,
)
from gduf_web_api.models import (
    AiHome,
    ArticleSummary,
    ClubSummary,
    CompetitionDetail,
    CompetitionFaq,
    CompetitionSummary,
    CompetitionTimelineItem,
    ContentDetail,
    ListResult,
    Notice,
    PageResult,
    PersonSummary,
    ResourceLink,
)

__version__ = "0.2.1"

__all__ = [
    "AiHome",
    "ArticleSummary",
    "ClubSummary",
    "CompetitionDetail",
    "CompetitionFaq",
    "CompetitionSummary",
    "CompetitionTimelineItem",
    "ContentDetail",
    "GdufClient",
    "GdufError",
    "InvalidPageError",
    "ListResult",
    "NetworkError",
    "Notice",
    "PageResult",
    "ParseError",
    "PersonSummary",
    "ResourceLink",
    "UnsupportedSourceError",
    "get_ai_detail",
    "get_ai_home",
    "get_ai_jfry",
    "get_ai_jgsz",
    "get_ai_jsjkxyjs",
    "get_ai_rgzn",
    "get_ai_rjgc",
    "get_ai_sjkxydsjjs",
    "get_ai_tzgg",
    "get_ai_xshenghd",
    "get_ai_xshuhd",
    "get_ai_xyjj",
    "get_ai_xyld",
    "get_ai_xyxw",
    "get_ai_yytjx",
    "get_ai_zrjs",
    "get_aijspt_bslb",
    "get_aijspt_bsxq",
    "get_aijspt_stlb",
    "get_aijspt_tzgg",
    "search_ai",
]
